export const list2 = [
  {
    title: "Amato Title",
    slug: "amato-title-q3tqpd",
    body:
      "Laudantium repellendus ut. Rerum commodi alias est aut beatae placeat quaerat nobis quisquam. Consequuntur exercitationem ab numquam atque sit possimus.",
    createdAt: "2021-05-05T13:09:12.884Z",
    updatedAt: "2021-05-05T13:09:12.884Z",
    tagList: [],
    description: "Projeto de automação Cypress",
    author: {
      username: "Lucas Amato",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "🔥 Finding a Path Forward with AngularJS",
    slug: "finding-a-path-forward-with-angularjs-m0on02",
    body:
      "In January of 2018 we laid out our plans for the final releases of AngularJS before entering long term support. Then in July 2020 we extended the LTS date to December 31st 2021 due to the global pandemic.\nWe understand that teams using AngularJS in production may have questions about what options are available to them. Let’s take a look at a few of the alternatives.\n\n☑️ Upgrade to Angular\nAngular, the successor to AngularJS, uses many of the same philosophies. Angular continues to move forward increasing stability, developer productivity and forging a new path forward for the development of scalable applications for the web. As a best practice we recommend that teams upgrade their applications to Angular.\nThe Angular team offers ngUpgrade, a library that lets you run Angular and AngularJS in the same application, allowing incremental migration. We defined best practices and a migration strategy for upgrading applications to Angular from AngularJS using ngUpgrade. Because applications vary in size and complexity the upgrade may require some flexibility. We also created a forum to collect best practices, and a migration tool to help analyze your application and make migration recommendations.\nThe upgrade guide gives detailed instructions on how to prepare your application for an upgrade and even includes code samples and examples. Head over to angular.io for more information.\nYou can find more resources like communities, courses, and more at angular.io/resources.\n\n☑️ Continue with the latest version of AngularJS\nIf upgrading to Angular isn’t an option at this time, then you can continue to rely on AngularJS. We expect that AngularJS applications that work now will continue to work in the future. All published versions of AngularJS on npm and bower will continue to be available. The framework will receive updates that cover security issues and breaking browser bugs until December 31st 2021. We don’t anticipate any changes being required by teams using AngularJS.\nBe mindful that this could trigger alerts about the use of unsupported software.\nIf teams need long term support after the December 31st 2021 date this is another option to consider.\n\n☑️ Extended Long Term Support\nWe know that many teams will need to continue to rely on AngularJS in the future, and that some of them need to show that they only use supported software. Companies have SLAs of their own or have to meet regulatory/compliance needs around support. There is a solution if you require ongoing support.\nThe independent team at XLTS.dev offers extended long term support for AngularJS. Starting January 1st 2022 XLTS.dev team will maintain a fork of the latest version of AngularJS and provide software updates that fit any of the following criteria:\nSecurity Patches: A security flaw is detected in XLTS for AngularJS\nBrowser Breaking Changes: One of the major browsers releases a version that will cause current production applications using the XLTS for AngularJS to stop working\njQuery Patches: The jQuery library releases a version that will cause current production applications using XLTS for AngularJS to stop working\nFind out more information over at https://xlts.dev/angularjs.\n\n☑️ The path forward\nAngularJS wouldn’t have been a success without you — the incredible community. We are thrilled about the future of Angular and are grateful for the lessons learned and road travelled with AngularJS. We will continue to build the future of the web with Angular and look forward to taking this journey with you.",
    createdAt: "2021-05-05T13:08:48.793Z",
    updatedAt: "2021-05-05T13:08:48.793Z",
    tagList: [],
    description: "upgrade to angular, and keep moving forward",
    author: {
      username: "test developer",
      bio: "i am an Angular developer",
      image:
        "https://www.google.co.in/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwi7hJOg7rDdAhXJO48KHaoNDt8QjRx6BAgBEAU&url=https%3A%2F%2Fwww.cbronline.com%2Fwhat-is%2Fwhat-is-a-url-4934011%2F&psig=AOvVaw399rhkpOB7ZYlUYs_LqvOt&ust=1536683493025576",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "title_210505_210621083",
    slug: "title_210505_210621083-mheotn",
    body: "article_markdown 210505_210621083",
    createdAt: "2021-05-05T13:06:27.003Z",
    updatedAt: "2021-05-05T13:06:27.003Z",
    tagList: [],
    description: "about_article: 210505_210621083",
    author: {
      username: "user210505_210621083",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "Apple Test",
    slug: "apple-test-gfqgqk",
    body: "this post is for testing purpose. **important**.",
    createdAt: "2021-05-05T12:52:25.450Z",
    updatedAt: "2021-05-05T12:52:25.450Z",
    tagList: ["AppleTest"],
    description: "About the test",
    author: {
      username: "Bijay",
      bio: null,
      image: "",
      following: false,
    },
    favorited: false,
    favoritesCount: 1,
  },
  {
    title: "rain",
    slug: "rain-rp0gp6",
    body: "more water is good",
    createdAt: "2021-05-05T12:46:01.500Z",
    updatedAt: "2021-05-05T12:46:01.500Z",
    tagList: ["water"],
    description: "rain",
    author: {
      username: "goodBoy",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "water",
    slug: "water-sv3tr8",
    body: "more is better",
    createdAt: "2021-05-05T12:44:21.841Z",
    updatedAt: "2021-05-05T12:44:21.841Z",
    tagList: ["water"],
    description: "drink",
    author: {
      username: "goodBoy",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "goodboy",
    slug: "goodboy-puv6dy",
    body: "good man",
    createdAt: "2021-05-05T12:43:27.058Z",
    updatedAt: "2021-05-05T12:43:27.058Z",
    tagList: [],
    description: "hello",
    author: {
      username: "goodBoy",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "11112",
    slug: "11112-gbmrxy",
    body: "44444",
    createdAt: "2021-05-05T12:42:49.486Z",
    updatedAt: "2021-05-05T12:42:49.486Z",
    tagList: [],
    description: "33333",
    author: {
      username: "goodBoy",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "111",
    slug: "111-nyq56g",
    body: "333",
    createdAt: "2021-05-05T12:38:29.004Z",
    updatedAt: "2021-05-05T12:38:29.004Z",
    tagList: ["4444"],
    description: "222",
    author: {
      username: "goodBoy",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "1111",
    slug: "1111-f4f3eh",
    body: "3333",
    createdAt: "2021-05-05T12:34:50.121Z",
    updatedAt: "2021-05-05T12:34:50.121Z",
    tagList: [],
    description: "2222",
    author: {
      username: "goodBoy",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "Test",
    slug: "test-e7gyd6",
    body: "Test 2",
    createdAt: "2021-05-05T12:21:23.686Z",
    updatedAt: "2021-05-05T12:21:23.686Z",
    tagList: [],
    description: "Test 1",
    author: {
      username: "Soso",
      bio: null,
      image: "",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "Anu123",
    slug: "anu123-rius7b",
    body: "Test",
    createdAt: "2021-05-05T12:21:22.812Z",
    updatedAt: "2021-05-05T12:21:22.812Z",
    tagList: [],
    description: "Karate",
    author: {
      username: "Anukarate",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "Anu123",
    slug: "anu123-vn24r",
    body: "Test",
    createdAt: "2021-05-05T12:21:22.636Z",
    updatedAt: "2021-05-05T12:21:22.636Z",
    tagList: [],
    description: "Karate",
    author: {
      username: "Anukarate",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "Anu123",
    slug: "anu123-ytjswz",
    body: "Test",
    createdAt: "2021-05-05T12:20:41.131Z",
    updatedAt: "2021-05-05T12:20:41.131Z",
    tagList: [],
    description: "Karate",
    author: {
      username: "Anukarate",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "Anu123",
    slug: "anu123-9b7twe",
    body: "Test",
    createdAt: "2021-05-05T12:20:41.027Z",
    updatedAt: "2021-05-05T12:20:41.027Z",
    tagList: [],
    description: "Karate",
    author: {
      username: "Anukarate",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "Anu123",
    slug: "anu123-xada1w",
    body: "Test",
    createdAt: "2021-05-05T12:19:35.365Z",
    updatedAt: "2021-05-05T12:19:35.365Z",
    tagList: [],
    description: "Karate",
    author: {
      username: "Anukarate",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "Anu123",
    slug: "anu123-vq6ecc",
    body: "Test",
    createdAt: "2021-05-05T12:18:13.486Z",
    updatedAt: "2021-05-05T12:18:13.486Z",
    tagList: [],
    description: "Karate",
    author: {
      username: "Anukarate",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "penghuo dragon",
    slug: "penghuo-dragon-r3g397",
    body: "## hello world \n- dragon",
    createdAt: "2021-05-05T12:17:12.458Z",
    updatedAt: "2021-05-05T12:17:12.458Z",
    tagList: [],
    description: "dragon",
    author: {
      username: "goodBoy",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "Article Title",
    slug: "article-title-l1w2ia",
    body: "Test article body",
    createdAt: "2021-05-05T12:02:19.129Z",
    updatedAt: "2021-05-05T12:02:19.129Z",
    tagList: [],
    description: "Test for update",
    author: {
      username: "AnnaB",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "О диванах.",
    slug: "-h8o5ix",
    body: "Spinner",
    createdAt: "2021-05-05T11:40:21.617Z",
    updatedAt: "2021-05-05T12:06:43.220Z",
    tagList: ["dfgh", "uyil", "qwerqwer"],
    description: "Я просто хочу матрас!",
    author: {
      username: "tdyjfgj",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
];
