export const list = [
  {
    title: "Test karate article",
    slug: "test-karate-article-8fihn7",
    body: "test1234",
    createdAt: "2021-05-04T04:47:32.077Z",
    updatedAt: "2021-05-04T04:47:32.077Z",
    tagList: [],
    description: "test123",
    author: {
      username: "Karate15",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "Moqorro",
    slug: "moqorro-zhxc7z",
    body:
      "Knowledge could be more valuable than gold, more deadly than a dagger.",
    createdAt: "2021-05-04T04:40:31.732Z",
    updatedAt: "2021-05-04T04:40:31.732Z",
    tagList: [],
    description: "Bayasabhad",
    author: {
      username: "Thala",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 1,
  },
  {
    title: "Myles",
    slug: "myles-ecfia7",
    body:
      "Why is it that when one man builds a wall, the next man immediately needs to know what's on the other side?",
    createdAt: "2021-05-04T04:40:30.924Z",
    updatedAt: "2021-05-04T04:40:30.924Z",
    tagList: [],
    description: "Elyria",
    author: {
      username: "Thala",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "Wow, it's aa mzing title",
    slug: "wow-it-s-aa-mzing-title-5o2sle",
    body:
      "A 9-year-old spends 81 years in his life sitting under the sun and enjoying life.",
    createdAt: "2021-05-04T03:58:05.853Z",
    updatedAt: "2021-05-04T03:58:05.853Z",
    tagList: [],
    description: "Who said a 90-year-old cannot code?",
    author: {
      username: "dalllsa",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "Test",
    slug: "test-y21gl7",
    body: "# Woah\n## this actually works\nCooooooool",
    createdAt: "2021-05-04T03:56:47.976Z",
    updatedAt: "2021-05-04T03:56:55.958Z",
    tagList: [],
    description: "Testing",
    author: {
      username: "HUTCH",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 1,
  },
  {
    title: "Test karate article",
    slug: "test-karate-article-778zej",
    body: "test1234",
    createdAt: "2021-05-04T03:54:34.444Z",
    updatedAt: "2021-05-04T03:54:34.444Z",
    tagList: [],
    description: "test123",
    author: {
      username: "Karate15",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 1,
  },
  {
    title: "bla bla arcticle",
    slug: "bla-bla-arcticle-90n5at",
    body: "bla bla test",
    createdAt: "2021-05-04T03:54:32.339Z",
    updatedAt: "2021-05-04T03:54:32.339Z",
    tagList: [],
    description: "test test",
    author: {
      username: "Karate15",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "Test karate article",
    slug: "test-karate-article-wjl9ba",
    body: "test1234",
    createdAt: "2021-05-04T03:53:42.400Z",
    updatedAt: "2021-05-04T03:53:42.400Z",
    tagList: [],
    description: "test123",
    author: {
      username: "Karate15",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "bla bla arcticle",
    slug: "bla-bla-arcticle-eme01t",
    body: "bla bla test",
    createdAt: "2021-05-04T03:53:41.300Z",
    updatedAt: "2021-05-04T03:53:41.300Z",
    tagList: [],
    description: "test test",
    author: {
      username: "Karate15",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "Test karate article",
    slug: "test-karate-article-rfotbf",
    body: "test1234",
    createdAt: "2021-05-04T03:52:36.805Z",
    updatedAt: "2021-05-04T03:52:36.805Z",
    tagList: [],
    description: "test123",
    author: {
      username: "Karate15",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "bla bla arcticle",
    slug: "bla-bla-arcticle-iic3al",
    body: "bla bla test",
    createdAt: "2021-05-04T03:52:35.880Z",
    updatedAt: "2021-05-04T03:52:35.880Z",
    tagList: [],
    description: "test test",
    author: {
      username: "Karate15",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "Test karate article",
    slug: "test-karate-article-2qh5qx",
    body: "test1234",
    createdAt: "2021-05-04T03:49:53.193Z",
    updatedAt: "2021-05-04T03:49:53.193Z",
    tagList: [],
    description: "test123",
    author: {
      username: "Karate15",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "bla bla arcticle",
    slug: "bla-bla-arcticle-zkjrlk",
    body: "bla bla test",
    createdAt: "2021-05-04T03:49:50.762Z",
    updatedAt: "2021-05-04T03:49:50.762Z",
    tagList: [],
    description: "test test",
    author: {
      username: "Karate15",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "cadsa",
    slug: "cadsa-1eytqu",
    body: "sada",
    createdAt: "2021-05-04T02:57:10.660Z",
    updatedAt: "2021-05-04T02:57:10.660Z",
    tagList: [],
    description: "sada",
    author: {
      username: "hoanghoatham123",
      bio: "qawdwad",
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "test",
    slug: "test-1va04",
    body: "rwfwefwef",
    createdAt: "2021-05-04T02:39:43.818Z",
    updatedAt: "2021-05-04T02:39:43.818Z",
    tagList: [],
    description: "test",
    author: {
      username: "olipv",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 2,
  },
  {
    title: "test",
    slug: "test-d90n0t",
    body: "rwfwefwef",
    createdAt: "2021-05-04T02:30:03.777Z",
    updatedAt: "2021-05-04T02:30:03.777Z",
    tagList: [],
    description: "test",
    author: {
      username: "olipv",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 1,
  },
  {
    title: "Test",
    slug: "test-gnhhkg",
    body: "Things",
    createdAt: "2021-05-04T02:26:25.053Z",
    updatedAt: "2021-05-04T02:26:25.053Z",
    tagList: [],
    description: "Stuff",
    author: {
      username: "Bob McAlice",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 2,
  },
  {
    title: "rnt",
    slug: "rnt-o8tuc6",
    body: "#asdfsdfsd",
    createdAt: "2021-05-04T01:39:41.072Z",
    updatedAt: "2021-05-04T01:39:41.072Z",
    tagList: [],
    description: "dddsdf",
    author: {
      username: "윤",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 0,
  },
  {
    title: "teste",
    slug: "teste-7k2ytg",
    body: "teste",
    createdAt: "2021-05-04T01:21:41.203Z",
    updatedAt: "2021-05-04T01:21:41.203Z",
    tagList: ["teste"],
    description: "teste",
    author: {
      username: "poincare",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 1,
  },
  {
    title: "aa",
    slug: "aa-p63fa",
    body: "sdsf",
    createdAt: "2021-05-03T23:56:09.077Z",
    updatedAt: "2021-05-03T23:56:09.077Z",
    tagList: [],
    description: "dc",
    author: {
      username: "eriknyk",
      bio: null,
      image: "https://static.productionready.io/images/smiley-cyrus.jpg",
      following: false,
    },
    favorited: false,
    favoritesCount: 1,
  },
];
